services:
  alcohol-store-backend:
    container_name: alcohol-store-backend
    build:
      context: ./backend
    command: npm run start:dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/be
      - be-nm:/usr/be/node_modules
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      alcohol-store-be:

  postgresql:
    container_name: postgresql
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      alcohol-store-be:

volumes:
  be-nm:
  postgres-data:

networks:
  alcohol-store-be:
